EmpMVC/Controllers/DepartmentController.cs
using EmpMVC.Data;
using EmpMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using X.PagedList;
using System.Drawing.Printing;
using X.PagedList.Extensions;

namespace EmpMVC.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly EmployeeDbContext _context;
        public DepartmentController(EmployeeDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(string sortOrder, string CurrentSort, int? page)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            ViewBag.CurrentSort = sortOrder;
            sortOrder = String.IsNullOrEmpty(sortOrder) ? "DeptName" : sortOrder;
            IPagedList<Department> departments = null;

            switch (sortOrder)
            {
                case "DeptName":
                    if (sortOrder.Equals(CurrentSort))
                        departments = _context.Departments.OrderByDescending
                                (m => m.DeptName).ToPagedList(pageIndex, pageSize);
                    else
                        departments = _context.Departments.OrderBy
                                (m => m.DeptName).ToPagedList(pageIndex, pageSize);
                    break;
            }
                    return View(departments);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Department dept) {
            if (ModelState.IsValid)
            {
                _context.Departments.Add(dept);
                _context.SaveChanges();
                TempData["ResultOk"] = "Record added!";
                return RedirectToAction("Index");
            }
            return View(dept);
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var dept = _context.Departments.Find(id);

            if (dept == null)
            {
                return NotFound();
            }
            return View(dept);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Department dept)
        {
            if (ModelState.IsValid)
            {
                _context.Departments.Update(dept);
                _context.SaveChanges();
                TempData["ResultOk"] = "Data Updated!";
                return RedirectToAction("Index");
            }

            return View(dept);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var dept = _context.Departments.Find(id);

            if (dept == null)
            {
                return NotFound();
            }
            return View(dept);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteDept(int? id)
        {
            var deleterecord = _context.Departments.Find(id);
            if (deleterecord == null)
            {
                return NotFound();
            }
            _context.Departments.Remove(deleterecord);
            _context.SaveChanges();
            TempData["ResultOk"] = "Data Deleted!";
            return RedirectToAction("Index");
        }
    }
}

EmpMVC/Controllers/EmployeeController.cs
using EmpMVC.Data;
using EmpMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using X.PagedList.Extensions;
using X.PagedList;

namespace EmpMVC.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly EmployeeDbContext _context;

        public EmployeeController(EmployeeDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(string sortOrder, string CurrentSort, int? page)
        {
            //IEnumerable<Employee> obj = _context.Employees
            //    .Include(e => e.Department).ToList();
            //return View(obj);
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            ViewBag.CurrentSort = sortOrder;
            sortOrder = String.IsNullOrEmpty(sortOrder) ? "FirstName" : sortOrder;
            IPagedList<Employee> employee = null;

            switch (sortOrder)
            {
                case "FirstName":
                    if (sortOrder.Equals(CurrentSort))
                        employee = _context.Employees.Include(e => e.Department).OrderByDescending
                                (m => m.FirstName).ToPagedList(pageIndex, pageSize);
                    else
                        employee = _context.Employees.Include(e => e.Department).OrderBy
                                (m => m.FirstName).ToPagedList(pageIndex, pageSize);
                    break;
                case "LastName":
                    if (sortOrder.Equals(CurrentSort))
                        employee = _context.Employees.Include(e => e.Department).OrderByDescending
                                (m => m.LastName).ToPagedList(pageIndex, pageSize);
                    else
                        employee = _context.Employees.Include(e => e.Department).OrderBy
                                (m => m.LastName).ToPagedList(pageIndex, pageSize);
                    break;
                case "Designation":
                    if (sortOrder.Equals(CurrentSort))
                        employee = _context.Employees.Include(e => e.Department).OrderByDescending
                                (m => m.Designation).ToPagedList(pageIndex, pageSize);
                    else
                        employee = _context.Employees.Include(e => e.Department).OrderBy
                                (m => m.Designation).ToPagedList(pageIndex, pageSize);
                    break;
                case "Address":
                    if (sortOrder.Equals(CurrentSort))
                        employee = _context.Employees.Include(e => e.Department).OrderByDescending
                                (m => m.Address).ToPagedList(pageIndex, pageSize);
                    else
                        employee = _context.Employees.Include(e => e.Department).OrderBy
                                (m => m.Address).ToPagedList(pageIndex, pageSize);
                    break;
                case "CreatedOn":
                    if (sortOrder.Equals(CurrentSort))
                        employee = _context.Employees.Include(e => e.Department).OrderByDescending
                                (m => m.CreatedOn).ToPagedList(pageIndex, pageSize);
                    else
                        employee = _context.Employees.Include(e => e.Department).OrderBy
                                (m => m.CreatedOn).ToPagedList(pageIndex, pageSize);
                    break;
                case "DeptName":
                    if (sortOrder.Equals(CurrentSort))
                        employee = _context.Employees.Include(e => e.Department).OrderByDescending
                                (m => m.Department.DeptName).ToPagedList(pageIndex, pageSize);
                    else
                        employee = _context.Employees.Include(e => e.Department).OrderBy
                                (m => m.Department.DeptName).ToPagedList(pageIndex, pageSize);
                    break;
            }
            return View(employee);
        }

        public async Task<IActionResult> Create()
        {
            var departments = await _context.Departments
            .FromSqlRaw("EXEC GetDepartments")
            .ToListAsync();

            
            ViewBag.DepartmentId = new SelectList(departments, "Id", "DeptName");
            return View();
        }
         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Employee emp)
        {
            if (ModelState.IsValid)
            {
                //_context.Employees.Add(emp);
                //_context.SaveChanges();
                //TempData["ResultOk"] = "Record added!";
                //return RedirectToAction("Index");
                _context.Database.ExecuteSqlRaw(
           "EXEC AddEmployee @FirstName, @LastName, @Designation, @DepartmentId, @Address",
           new SqlParameter("@FirstName", emp.FirstName),
           new SqlParameter("@LastName", emp.LastName),
           new SqlParameter("@Designation", emp.Designation),
           new SqlParameter("@DepartmentId", emp.DepartmentId),
           new SqlParameter("@Address", emp.Address)
           );
                _context.SaveChanges();
                TempData["ResultOk"] = "Record added!";
                return RedirectToAction("Index");
            }
            return View(emp);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var emp = _context.Employees.Find(id);

            if (emp == null)
            {
                return NotFound();
            }
            var departments = await _context.Departments
            .FromSqlRaw("EXEC GetDepartments")
            .ToListAsync();


            ViewBag.DepartmentId = new SelectList(departments, "Id", "DeptName");
            return View(emp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Employee emp)
        {
            if (ModelState.IsValid)
            {
                _context.Database.ExecuteSqlRaw(
           "EXEC UpdateEmployee @EmpId, @FirstName, @LastName, @Designation, @DepartmentId, @Address",
           new SqlParameter("@EmpId", emp.EmployeeId),
           new SqlParameter("@FirstName", emp.FirstName),
           new SqlParameter("@LastName", emp.LastName),
           new SqlParameter("@Designation", emp.Designation),
           new SqlParameter("@DepartmentId", emp.DepartmentId),
           new SqlParameter("@Address", emp.Address)
           );
                _context.SaveChanges();
                TempData["ResultOk"] = "Data Updated!";
                return RedirectToAction("Index");
            }

            return View(emp);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var emp = _context.Employees.Find(id);

            if (emp == null)
            {
                return NotFound();
            }
            var departments = await _context.Departments
            .FromSqlRaw("EXEC GetDepartments")
            .ToListAsync();


            ViewBag.DepartmentId = new SelectList(departments, "Id", "DeptName");
            return View(emp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteEmp(int? EmployeeId)
        {
            var deleterecord = _context.Employees.Find(EmployeeId);
            if (deleterecord == null)
            {
                return NotFound();
            }
            _context.Employees.Remove(deleterecord);
            _context.SaveChanges();
            TempData["ResultOk"] = "Data Deleted!";
            return RedirectToAction("Index");
        }
    }
}

EmpMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmpMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmpMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmpMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarView" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                View
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarAdd">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Employee" asp-action="Index">View Employee</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Department" asp-action="Index">View Department</a></li>
                                <!-- Add more links as needed -->
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarAdd" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Add
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarAdd">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Employee" asp-action="Create">Add Employee</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Department" asp-action="Create">Add Department</a></li>
                                <!-- Add more links as needed -->
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EmpMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>